services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - php
  #   networks:
  #     - web_network

  # php:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-php
  #   volumes:
  #     - .:/var/www/html
  #   expose:
  #     - 9000
  #   networks:
  #     - web_network

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    # depends_on:
    #   - web
    networks:
      - web_network

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - .:/var/www/html
  #   depends_on:
  #     - nginx
  #   entrypoint: /bin/sh -c "while :; do sleep 1; done & certbot certonly --webroot --webroot-path=/var/www/html/public_html --email your.email@example.com --agree-tos --no-eff-email -d yourdomain.com;"

networks:
  web_network:
    driver: bridge
